### ISSUE TITLE
.withSearchQuery not working? 

### ISSUE THREAD

**Issue by DaireNiC** [hassie-dash/NewsAPI.NET#1]
I'm looking to achieve the same results as this query using your API wrapper. 

- Query : https://newsapi.org/v2/everything?q=bitcoin&apiKey=~myapikey~

However, I'm getting this exception:
News API HTTP Exception - parametersMissing: Required parameters are missing, the scope of your search is too broad. Please set any of the following required parameters and try again: q, sources, domains.

- My everything request: 
            INewsArticles newsArticles = await newsClient.GetEverything(new EverythingBuilder()
            .WithSearchQuery("bitcoin")
            .WithSortOrder(SortOrder.PUBLISHED_AT)
            .Build());

Is there something I'm doing wrong here? 

Thanks!

**Comment by hassie-dash** [comment]
Hey, thanks for opening an issue. I just looked through my code and indeed I have made an error when building the query. I will fix this and update as  soon as possible. Thanks!

**Comment by hassie-dash** [comment]
Update has been published and should be available to download soon :)
